plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - readme.md
theme: jekyll-theme-cayman
title: Expressly Express Zero
baseurl: "education-expressly-express-zero"
url: ""
